# Generated by Django 5.0.4 on 2024-10-20 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_rename_owener_ordereditem_owner_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordereditem',
            old_name='owner',
            new_name='owener',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.IntegerField(choices=[(2, 'ORDER_PROCESSED'), (3, 'ORDER_DELIVERED'), (4, 'ORDER_REJECTED')], default=0),
        ),
    ]
